[workspace]
resolver = "2"
members = [
  "todo",
  "todo-api",
  "todo-desktop",
  "todo-macro",
  "todo-mobile",
  "todo-server",
  "todo-ui",
  "todo-web",
]
default-members = ["todo"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"
authors = ["Lucas Gager <evest.dev@gmail.com>"]
repository = "https://github.com/Ev357/todo-rs"
rust-version = "1.100.0"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"
incremental = false

[profile.dev.package."*"]
debug = false

[workspace.dependencies]
todo-api = { path = "todo-api" }
todo-macro = { path = "todo-macro" }
todo-server = { path = "todo-server", default-features = false }

dioxus = { git = "https://github.com/Ev357/dioxus", branch = "feat/query-method" }
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "uuid"] }
tokio = { version = "1.53.1", features = ["full"] }
color-eyre = "0.6.5"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_urlencoded = "0.7.1"
axum = { git = "https://github.com/tokio-rs/axum", features = ["macros"] }
tower = "0.5.3"
reqwest = { version = "0.13.4", features = ["json"] }
indexmap = { version = "2.14.2", features = ["serde"] }
uuid = { version = "1.26.1", features = ["serde"] }
gloo-timers = { version = "0.4.0", features = ["futures"] }
clap = { version = "4.6.6", features = ["derive"] }
clap_complete = "4.6.9"
clap_complete_nushell = "4.6.2"
toml = "1.1.6"
tabled = "0.22.0"

[workspace.lints.clippy]
wildcard_imports = "warn"
unwrap_used = "warn"
dbg_macro = "warn"
todo = "warn"
