[package]
name = "todo-desktop"
description = "Desktop version of todo-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }

[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server"]
