[package]
name = "todo-desktop"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
todo-ui = { workspace = true }

[features]
default = []
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "todo-ui/server"]
