[package]
name = "todo-web"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
todo-api = { workspace = true }
todo-server = { workspace = true, default-features = false }

dioxus = { workspace = true, features = ["router", "fullstack"] }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "todo-api/server"]
