[package]
name = "todo-api"
description = "Dioxus backend api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
todo-server = { workspace = true, default-features = false }

dioxus = { workspace = true, features = ["fullstack"] }
reqwest = { workspace = true, optional = true }
serde = { workspace = true }
uuid = { workspace = true }

[features]
server = ["dioxus/server", "dep:reqwest"]
